<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../../stores/auth'
import BaseButton from '../../components/forms/BaseButton.vue'

import { useToast } from 'vue-toastification'

const router = useRouter()
const authStore = useAuthStore()
const toast = useToast()

const code = ref('')
const errorMsg = ref('')

async function handleVerify() {
  errorMsg.value = ''
  try {
    await authStore.verifyTwoFactor(code.value)
    toast.success('Identity verified. Accessing console...')
    router.push('/dashboard')
  } catch (error: any) {
    toast.error(error.response?.data?.message || error.message || 'Invalid or expired authentication code.')
    errorMsg.value = error.response?.data?.message || error.message || 'Invalid or expired authentication code.'
  }
}
</script>

<template>
  <div class="min-h-screen bg-dark-bg flex relative overflow-hidden">
    <div class="glow-orb w-[400px] h-[400px] bg-indigo-600/15 -top-32 -left-24"></div>
    <div class="glow-orb w-[320px] h-[320px] bg-cyan-600/10 bottom-16 right-10"></div>

    <div class="w-full flex flex-col items-center justify-center p-6 sm:p-12 z-10">
      <div class="mb-10 flex flex-col items-center gap-3">
        <img src="/blocpoint-white.png" alt="BlocPoint" class="h-8 w-auto" />
        <h1 class="text-2xl font-semibold text-white">Multi-factor verification</h1>
        <p class="text-sm text-slate-400 max-w-sm text-center">
          For your security, please enter the 6-digit code from your authenticator app to complete
          sign-in.
        </p>
      </div>

      <div class="w-full max-w-md">
        <div class="glass-panel p-8 rounded-2xl relative overflow-hidden group">
          <div
            class="absolute -top-1/2 -right-1/2 w-full h-full bg-indigo-500/5 blur-[100px] pointer-events-none group-hover:bg-indigo-500/10 transition-all duration-700"
          ></div>

          <form @submit.prevent="handleVerify" class="space-y-6 relative z-10">
            <div class="space-y-2">
              <label class="text-sm font-medium text-slate-300 ml-1">Authenticator Code</label>
              <input
                v-model="code"
                type="text"
                inputmode="numeric"
                maxlength="6"
                placeholder="••••••"
                required
                class="form-input-premium w-full text-center tracking-[0.5em] text-lg"
              />
              <p class="text-xs text-slate-500 mt-1 ml-1">
                Enter the 6‑digit code generated by your TOTP authenticator.
              </p>
            </div>

            <transition name="fade">
              <div
                v-if="errorMsg"
                class="flex items-center gap-2 p-3 bg-red-500/10 border border-red-500/20 rounded-xl"
              >
                <div class="w-1.5 h-1.5 rounded-full bg-red-500 animate-pulse"></div>
                <p class="text-xs text-red-500 font-medium">{{ errorMsg }}</p>
              </div>
            </transition>

            <BaseButton
              variant="primary"
              class="w-full py-3.5 group"
              :loading="authStore.loading"
              type="submit"
            >
              <span class="flex items-center gap-2">
                Verify & Enter Console
              </span>
            </BaseButton>
          </form>
        </div>

        <div class="mt-6 text-center">
          <p class="text-xs text-slate-500">
            Lost access to your authenticator?
            <span class="text-indigo-400">Contact a BlocPoint super admin to reset your 2FA.</span>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s ease, transform 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(-4px);
}
</style>


